PgUp::
    SendInput, B
    Sleep, 200
    SendInput, A
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, F
    Sleep, 200
    SendInput, 9
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, F
    Sleep, 200
    SendInput, F
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, B
    Sleep, 200
    SendInput, 0
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, 0
    Sleep, 200
    SendInput, 1
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, E
    Sleep, 200
    SendInput, E
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, B
    Sleep, 200
    SendInput, A
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, F
    Sleep, 200
    SendInput, 8
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, F
    Sleep, 200
    SendInput, F
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, E
    Sleep, 200
    SendInput, C
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, 3
    Sleep, 200
    SendInput, C
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, 0
    Sleep, 200
    SendInput, 1
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, 7
    Sleep, 200
    SendInput, 5
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, F
    Sleep, 200
    SendInput, 8
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, B
    Sleep, 200
    SendInput, 9
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, 0
    Sleep, 200
    SendInput, 8
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, 0
    Sleep, 200
    SendInput, 0
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, B
    Sleep, 200
    SendInput, 0
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, 8
    Sleep, 200
    SendInput, 0
    return
