PgUp::
    SendInput, B
    Sleep, 200
    SendInput, A
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, F
    Sleep, 200
    SendInput, 9
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, F
    Sleep, 200
    SendInput, F
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, E
    Sleep, 200
    SendInput, C
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, B
    Sleep, 200
    SendInput, A
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, F
    Sleep, 200
    SendInput, 8
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, F
    Sleep, 200
    SendInput, F
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, E
    Sleep, 200
    SendInput, E
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, E
    Sleep, 200
    SendInput, B
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, F
    Sleep, 200
    SendInput, 6
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, B
    Sleep, 200
    SendInput, A
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, F
    Sleep, 200
    SendInput, 9
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, F
    Sleep, 200
    SendInput, F
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, E
    Sleep, 200
    SendInput, C
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, 3
    Sleep, 200
    SendInput, C
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, 0
    Sleep, 200
    SendInput, 1
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, 7
    Sleep, 200
    SendInput, 5
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, F
    Sleep, 200
    SendInput, 8
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, B
    Sleep, 200
    SendInput, 9
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, 0
    Sleep, 200
    SendInput, 8
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, 0
    Sleep, 200
    SendInput, 0
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, B
    Sleep, 200
    SendInput, 0
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, 8
    Sleep, 200
    SendInput, 0
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, B
    Sleep, 200
    SendInput, A
    Sleep, 200
    SendInput, ,
    Sleep, 200
    SendInput, F
    Sleep, 200
    SendInput, 8
    Sleep, 200
    SendInput, ,
    SendInput, F
    Sleep, 200
    SendInput, F
    Sleep, 200
    SendInput, ,
    SendInput, E
    Sleep, 200
    SendInput, E
    Sleep, 200
    SendInput, ,
    SendInput, D
    Sleep, 200
    SendInput, 0
    Sleep, 200
    SendInput, ,
    SendInput, E
    Sleep, 200
    SendInput, 8
    Sleep, 200
    SendInput, ,
    SendInput, E
    Sleep, 200
    SendInput, 8
    Sleep, 200
    SendInput, ,
    SendInput, 0
    Sleep, 200
    SendInput, 2
    Sleep, 200
    SendInput, ,
    SendInput, 0
    Sleep, 200
    SendInput, 0
    Sleep, 200
    SendInput, ,
    SendInput, E
    Sleep, 200
    SendInput, 2
    Sleep, 200
    SendInput, ,
    SendInput, F
    Sleep, 200
    SendInput, 5
    Sleep, 200
    SendInput, ,
    SendInput, 5
    Sleep, 200
    SendInput, 1
    Sleep, 200
    SendInput, ,
    SendInput, B
    Sleep, 200
    SendInput, 9
    Sleep, 200
    SendInput, ,
    SendInput, 6
    Sleep, 200
    SendInput, 4
    Sleep, 200
    SendInput, ,
    SendInput, 0
    Sleep, 200
    SendInput, 0
    Sleep, 200
    SendInput, ,
    SendInput, 8
    Sleep, 200
    SendInput, B
    Sleep, 200
    SendInput, ,
    SendInput, D
    Sleep, 200
    SendInput, 1
    Sleep, 200
    SendInput, ,
    SendInput, B
    Sleep, 200
    SendInput, 9
    Sleep, 200
    SendInput, ,
    SendInput, F
    Sleep, 200
    SendInput, F
    Sleep, 200
    SendInput, ,
    SendInput, F
    Sleep, 200
    SendInput, F
    Sleep, 200
    SendInput, ,
    SendInput, E
    Sleep, 200
    SendInput, 2
    Sleep, 200
    SendInput, ,
    SendInput, F
    Sleep, 200
    SendInput, E
    Sleep, 200
    SendInput, ,
    SendInput, 8
    Sleep, 200
    SendInput, B
    Sleep, 200
    SendInput, ,
    SendInput, C
    Sleep, 200
    SendInput, A
    Sleep, 200
    SendInput, ,
    SendInput, E
    Sleep, 200
    SendInput, 2
    Sleep, 200
    SendInput, ,
    SendInput, F
    Sleep, 200
    SendInput, 5
    Sleep, 200
    SendInput, ,
    SendInput, 5
    Sleep, 200
    SendInput, 9
    Sleep, 200
    SendInput, ,
    SendInput, 3
    Sleep, 200
    SendInput, 2
    Sleep, 200
    SendInput, ,
    SendInput, E
    Sleep, 200
    SendInput, D
    Sleep, 200
    SendInput, ,
    SendInput, C
    Sleep, 200
    SendInput, 3
    Sleep, 200
    SendInput, .
    return
